"""add coupon to orders

Revision ID: 3295d8d2726f
Revises: 0f5d90fc9379
Create Date: 2026-07-23 10:00:39.076971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3295d8d2726f'
down_revision: Union[str, Sequence[str], None] = '0f5d90fc9379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'coupon_id')
    # ### end Alembic commands ###
